### ISSUE TITLE
deadbeef: playlist.c:319: plt_unref: Assertion `plt->refc > 0' failed.

### ISSUE THREAD

**Issue by jtojnar** [Serranya/deadbeef-mpris2-plugin#39]
I have installed DeaDBeeF 0.7.2 on Ubuntu 18.10 using the deb package. When I add mpris.so (revision 0d4dc8f) to `~/.local/lib/deadbeef`, DeaDBeeF crashes on start up. I have removed `~/.config/deadbeef` and all other plugins from the `~/.local/lib/deadbeef`.

```
$ /opt/deadbeef/bin/deadbeef
starting deadbeef 0.7.2 [static]
server_start
INFO: unlink socket: No such file or directory
failed to load config file
created an empty config
searching for GUI plugins in /home/jtojnar/.local/lib64/deadbeef
searching for GUI plugins in /home/jtojnar/.local/lib/deadbeef
load_plugin_dir /home/jtojnar/.local/lib/deadbeef: scandir found 4 files
searching for GUI plugins in /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 53 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
found selected GUI plugin: GTK2
loading plugin /opt/deadbeef/lib/deadbeef/ddb_gui_GTK2.so
loading plugins from /home/jtojnar/.local/lib64/deadbeef
loading plugins from /home/jtojnar/.local/lib/deadbeef
load_plugin_dir /home/jtojnar/.local/lib/deadbeef: scandir found 4 files
loading plugin /home/jtojnar/.local/lib/deadbeef/mpris.so
loading plugins from /opt/deadbeef/lib/deadbeef
load_plugin_dir /opt/deadbeef/lib/deadbeef: scandir found 53 files
loading plugin /opt/deadbeef/lib/deadbeef/aac.so
loading plugin /opt/deadbeef/lib/deadbeef/adplug.so
loading plugin /opt/deadbeef/lib/deadbeef/alac.so
loading plugin /opt/deadbeef/lib/deadbeef/alsa.so
loading plugin /opt/deadbeef/lib/deadbeef/artwork.so
loading plugin /opt/deadbeef/lib/deadbeef/cdda.so
loading plugin /opt/deadbeef/lib/deadbeef/converter.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/converter_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/dca.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_ao.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_dumb.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_mono2stereo.so
loading plugin /opt/deadbeef/lib/deadbeef/ddb_shn.so
loading plugin /opt/deadbeef/lib/deadbeef/dsp_libsrc.so
loading plugin /opt/deadbeef/lib/deadbeef/ffap.so
loading plugin /opt/deadbeef/lib/deadbeef/ffmpeg.so
loading plugin /opt/deadbeef/lib/deadbeef/flac.so
loading plugin /opt/deadbeef/lib/deadbeef/gme.so
loading plugin /opt/deadbeef/lib/deadbeef/hotkeys.so
loading plugin /opt/deadbeef/lib/deadbeef/in_sc68.so
loading plugin /opt/deadbeef/lib/deadbeef/lastfm.so
loading plugin /opt/deadbeef/lib/deadbeef/m3u.so
loading plugin /opt/deadbeef/lib/deadbeef/mms.so
loading plugin /opt/deadbeef/lib/deadbeef/mp3.so
loading plugin /opt/deadbeef/lib/deadbeef/musepack.so
loading plugin /opt/deadbeef/lib/deadbeef/notify.so
loading plugin /opt/deadbeef/lib/deadbeef/nullout.so
loading plugin /opt/deadbeef/lib/deadbeef/oss.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/pulse.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexec.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk2.so
loading plugin /opt/deadbeef/lib/deadbeef/shellexecui_gtk3.so
loading plugin /opt/deadbeef/lib/deadbeef/sid.so
loading plugin /opt/deadbeef/lib/deadbeef/sndfile.so
loading plugin /opt/deadbeef/lib/deadbeef/supereq.so
loading plugin /opt/deadbeef/lib/deadbeef/tta.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_curl.so
loading plugin /opt/deadbeef/lib/deadbeef/vfs_zip.so
loading plugin /opt/deadbeef/lib/deadbeef/vorbis.so
loading plugin /opt/deadbeef/lib/deadbeef/vtx.so
loading plugin /opt/deadbeef/lib/deadbeef/wavpack.so
loading plugin /opt/deadbeef/lib/deadbeef/wildmidi.so
loading plugin /opt/deadbeef/lib/deadbeef/wma.so
deadbeef: playlist.c:319: plt_unref: Assertion `plt->refc > 0' failed.
fish: “/opt/deadbeef/bin/deadbeef” terminated by signal SIGABRT (Abort)
```

This is the stack trace:

```ShellSession
$ coredumpctl gdb
           PID: 5617 (deadbeef-main)
           UID: 1000 (jtojnar)
           GID: 1000 (jtojnar)
        Signal: 6 (ABRT)
     Timestamp: Thu 2018-10-25 20:23:31 CEST (32min ago)
  Command Line: /opt/deadbeef/bin/deadbeef
    Executable: /opt/deadbeef/bin/deadbeef
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (jtojnar)
       Boot ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    Machine ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      Hostname: jtojnar
       Storage: /var/lib/systemd/coredump/core.deadbeef-main.1000.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.5617.1540491811000000.lz4
       Message: Process 5617 (deadbeef-main) of user 1000 dumped core.
                
                Stack trace of thread 5618:
                #0  0x00007f6a2c807077 __GI_raise (libc.so.6)
                #1  0x00007f6a2c7e8535 __GI_abort (libc.so.6)
                #2  0x00007f6a2c7e840f __assert_fail_base (libc.so.6)
                #3  0x00007f6a2c7f8142 __GI___assert_fail (libc.so.6)
                #4  0x0000000000402bea n/a (deadbeef)
                #5  0x000000000040905a n/a (deadbeef)
                #6  0x00007f6a273ca1c5 n/a (/home/jtojnar/.local/lib/deadbeef/mpris.so)
                #7  0x00007f6a273cbb07 n/a (/home/jtojnar/.local/lib/deadbeef/mpris.so)
                #8  0x00007f6a2a905469 n/a (libgio-2.0.so.0)
                #9  0x00007f6a2b254ae8 g_main_context_dispatch (libglib-2.0.so.0)
                #10 0x00007f6a2b254ed8 n/a (libglib-2.0.so.0)
                #11 0x00007f6a2b2551d2 g_main_loop_run (libglib-2.0.so.0)
                #12 0x00007f6a273cc92d n/a (/home/jtojnar/.local/lib/deadbeef/mpris.so)
                #13 0x00007f6a2b27d135 n/a (libglib-2.0.so.0)
                #14 0x00007f6a2c9b8164 start_thread (libpthread.so.0)
                #15 0x00007f6a2c8e0def __clone (libc.so.6)
                
                Stack trace of thread 5619:
                #0  0x00007f6a2c9be2eb futex_wait_cancelable (libpthread.so.0)
                #1  0x00007f6a262dcba9 n/a (artwork.so)
                #2  0x00007f6a2c9b8164 start_thread (libpthread.so.0)
                #3  0x00007f6a2c8e0def __clone (libc.so.6)
                
                Stack trace of thread 5620:
                #0  0x00007f6a2c8a46a0 __GI___nanosleep (libc.so.6)
                #1  0x00007f6a2c8d77d4 usleep (libc.so.6)
                #2  0x00007f6a262dd0e2 n/a (artwork.so)
                #3  0x00007f6a2c9b8164 start_thread (libpthread.so.0)
                #4  0x00007f6a2c8e0def __clone (libc.so.6)
                
                Stack trace of thread 5622:
                #0  0x00007f6a2c8d46d9 __GI___poll (libc.so.6)
                #1  0x00007f6a2b254e46 n/a (libglib-2.0.so.0)
                #2  0x00007f6a2b254f6c g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f6a2b254fb1 n/a (libglib-2.0.so.0)
                #4  0x00007f6a2b27d135 n/a (libglib-2.0.so.0)
                #5  0x00007f6a2c9b8164 start_thread (libpthread.so.0)
                #6  0x00007f6a2c8e0def __clone (libc.so.6)
                
                Stack trace of thread 5624:
                #0  0x00007f6a2c8d46d9 __GI___poll (libc.so.6)
                #1  0x00007f6a2b254e46 n/a (libglib-2.0.so.0)
                #2  0x00007f6a2b2551d2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f6a2a9147b6 n/a (libgio-2.0.so.0)
                #4  0x00007f6a2b27d135 n/a (libglib-2.0.so.0)
                #5  0x00007f6a2c9b8164 start_thread (libpthread.so.0)
                #6  0x00007f6a2c8e0def __clone (libc.so.6)
                
                Stack trace of thread 5623:
                #0  0x00007f6a2c8da219 syscall (libc.so.6)
                #1  0x00007f6a2b29b75a g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007f6a2b227061 n/a (libglib-2.0.so.0)
                #3  0x00007f6a2b27dc12 n/a (libglib-2.0.so.0)
                #4  0x00007f6a2b27d135 n/a (libglib-2.0.so.0)
                #5  0x00007f6a2c9b8164 start_thread (libpthread.so.0)
                #6  0x00007f6a2c8e0def __clone (libc.so.6)
                
                Stack trace of thread 5617:
                #0  0x00007f6a2c8d46d9 __GI___poll (libc.so.6)
                #1  0x00007f6a29f609b7 n/a (libxcb.so.1)
                #2  0x00007f6a29f5e751 xcb_connect_to_fd (libxcb.so.1)
                #3  0x00007f6a29f625a4 xcb_connect_to_display_with_auth_info (libxcb.so.1)
                #4  0x00007f6a2affacd2 _XConnectXCB (libX11.so.6)
                #5  0x00007f6a2afeb892 XOpenDisplay (libX11.so.6)
                #6  0x00007f6a23657081 n/a (hotkeys.so)
                #7  0x0000000000406ac4 n/a (deadbeef)
                #8  0x000000000040346d n/a (deadbeef)
                #9  0x00007f6a2c7ea09b __libc_start_main (libc.so.6)
                #10 0x0000000000403985 n/a (deadbeef)

GNU gdb (Ubuntu 8.2-0ubuntu1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/deadbeef/bin/deadbeef...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 5618]
[New LWP 5619]
[New LWP 5620]
[New LWP 5622]
[New LWP 5624]
[New LWP 5623]
[New LWP 5617]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/deadbeef/bin/deadbeef'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f6a1ecc8700 (LWP 5618))]
(gdb) bt
#0  0x00007f6a2c807077 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6a2c7e8535 in __GI_abort () at abort.c:79
#2  0x00007f6a2c7e840f in __assert_fail_base
    (fmt=0x7f6a2c974858 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x433013 "plt->refc > 0", file=0x433008 "playlist.c", line=319, function=<optimized out>) at assert.c:92
#3  0x00007f6a2c7f8142 in __GI___assert_fail
    (assertion=0x433013 "plt->refc > 0", file=0x433008 "playlist.c", line=319, function=0x43358c "plt_unref") at assert.c:101
#4  0x0000000000402bea in  ()
#5  0x000000000040905a in  ()
#6  0x00007f6a273ca1c5 in getMetadataForTrack () at /home/jtojnar/.local/lib/deadbeef/mpris.so
#7  0x00007f6a273cbb07 in onPlayerGetPropertyHandler () at /home/jtojnar/.local/lib/deadbeef/mpris.so
#8  0x00007f6a2a905469 in invoke_get_all_properties_in_idle_cb (_data=0x7f6a04009750)
    at ../../../../gio/gdbusconnection.c:4485
#9  0x00007f6a2b254ae8 in g_main_dispatch (context=0x7f6a10001c00) at ../../../../glib/gmain.c:3182
#10 0x00007f6a2b254ae8 in g_main_context_dispatch (context=context@entry=0x7f6a10001c00)
    at ../../../../glib/gmain.c:3847
#11 0x00007f6a2b254ed8 in g_main_context_iterate
    (context=0x7f6a10001c00, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../../glib/gmain.c:3920
#12 0x00007f6a2b2551d2 in g_main_loop_run (loop=0x7f6a10019f00) at ../../../../glib/gmain.c:4116
#13 0x00007f6a273cc92d in startServer () at /home/jtojnar/.local/lib/deadbeef/mpris.so
#14 0x00007f6a2b27d135 in g_thread_proxy (data=0x82f050) at ../../../../glib/gthread.c:784
#15 0x00007f6a2c9b8164 in start_thread (arg=<optimized out>) at pthread_create.c:486
#16 0x00007f6a2c8e0def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) quit
```

**Comment by jtojnar** [comment]
Same issue with deadbeef 1.8.

**Comment by Serranya** [comment]
Thank you for reporting this. I will take a look.

**Comment by Serranya** [comment]
Can you please try if revision https://github.com/Serranya/deadbeef-mpris2-plugin/commit/1719c2e4e2f2dde6c4fdb6888c8a790fffd9fcd2 fixes this issue?

**Comment by jtojnar** [comment]
Can confirm this works.

**Comment by jtojnar** [comment]
Thank you.
